baseURL = "https://elohim666.github.io/"
languageCode = "en-us"
title = "3l0h1m.s3c"
theme = "elfterm"

[params]
  author = "elohim"
  description = "web · mobile · active directory · binary exploitation · exploit dev · low level"
  email = "anas.souiri@hotmail.com"
  twitter = "0x1nf0"
  github = "elohim666"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false
    lineNos = false
    guessSyntax = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
